package com.example.eyickanak.fragments;

/*Project Name: Kanak-Smart Composting
        Author List : Varad Gorhe ,Team Leader
        Filename    : FragmentInfo.java
        Global Variables:-
        Functions   :
 */


import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.fragment.app.Fragment;

import com.example.eyickanak.R;
import com.example.eyickanak.SignIn;



public class FragmentInfo extends Fragment {

    /*We have created a User manual for the app.This user manual is stored in storage of firebase .
  The link to the user manual which is generated by the firebase is assigned to a String variable pdfFileUri.
  When 'Download' button is pressed,the onClick() method is called and a new intent takes the user to the downloaded pdf.
*/


    String pdfFileUrl = "https://firebasestorage.googleapis.com/v0/b/kanak-96289.appspot.com/o/USER_MANUAL.pdf?alt=media&token=4aebf738-f112-4423-a631-a574fb86dcc4";

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_fragment_info, container, false);

        view.findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(Intent.ACTION_VIEW);
                intent.setData(Uri.parse(pdfFileUrl));
                startActivity(intent);
            }
        });


        return view;
    }


}
